### ISSUE TITLE
Production

### ISSUE THREAD

**Issue by Gameghostify** [dallasbeek/Dapper.Database#21]
First of all, thank you for making this awesome library.

This is more feature complete than anything else out there (even Dapper.Contrib) in my opinion, amazing work!!

That being said, is this library ready to be used in prod? Are there performance concerns? 

And if not, when do you think this could be used in prod by the masses?

**Comment by dallasbeek** [comment]
Performance wise it's pretty good, not as performant as I'd like (nothing ever is) but that's because it does a fair amount of attribute reflection to build the queries. I am building an application using it and although it isn't technically live in production I have yet to run into a show stopping issue as a result of this library and have every intention of launching with it.

**Comment by dallasbeek** [comment]
Have you tried using the T4 template?
https://github.com/dallasbeek/Dapper.Database/blob/master/T4Templates/CodeGen.tt.

It will generate all the classes with the attributes.  This is what you would call database first development.

**Comment by Gameghostify** [comment]
@dallasbeek Thank you so much for your swift response!

I didnt yet get to try using t4 templates but that'll hopefully change soon.

Thank you for creating and maintaining an awesome library :)
