### ISSUE TITLE
postgresql 区分字段大小写，需要在字段上用 双引号包围

### ISSUE THREAD

**Issue by niuniu007** [dallasbeek/Dapper.Database#48]
[Column(@"realId")]
        public string RealId { get; set; }
会生成这样的语句：
`select bwround."id" AS Id, bwround.appid AS Appid, bwround.realId `
在postresql中 realId  要使用 双引号包裹，因为他含有大写字母，所以正确的应该是：
`select bwround."id" AS Id, bwround.appid AS Appid, bwround."realId"`

在PostgresAdapter.cs文件中修正这个问题：
```

       /// <summary>
       ///     Returns the format for column
       /// </summary>
       public override string EscapeColumn(string value) => $@"""{value}""";
```

**Comment by dallasbeek** [comment]
Translated
    [Column(@"realId")]
    public string RealId { get; set; }
会生成这样的语句：**Statements like this will be generated:**
select bwround."id" AS Id, bwround.appid AS Appid, bwround.realId 
在postresql中 realId 要使用 双引号包裹，因为他含有大写字母，所以正确的应该是：
**In postresql, realId should be wrapped in double quotes because it contains uppercase letters, so the correct one should be:**
select bwround."id" AS Id, bwround.appid AS Appid, bwround."realId"

在PostgresAdapter.cs文件中修正这个问题：
**Fix this problem in the PostgresAdapter.cs file:**

       /// <summary>
       ///     Returns the format for column
       /// </summary>
       public override string EscapeColumn(string value) => $@"""{value}""";

**Comment by dallasbeek** [comment]
Applying public override string EscapeColumn(string value) => $@"""{value}"""; broke many tests

I suspect your column names have quotes (which I think is possible in postgres) i.e. "realId"

Try putting the quotes around the column attribute
 [Column(@"""realId""")]

**Comment by Anda001** [comment]
NO,Sir. when I use column like below,in postgresql, it converts to wrong item in sql string, 
```
  [Column("is_statusAsk")]
  public int IsStatusAsk { get; set; }
```

and I changed the PostgresAdapter.cs  like this,it fixed the problem.
```

        public override string EscapeColumn(string value) => $"\"{value}\"";
```

the poster is right.
